name: 🚀 ProxyHub Auto Update

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🔁 Run full scraping & processing
      run: |
        python scrape.py
        python filter.py
        python geo.py
        python convert_to_csv.py

    - name: 📤 Commit updated proxies (only if changed)
      run: |
        git config user.name "proxyhub-bot"
        git config user.email "proxyhub@users.noreply.github.com"
        git add output/
        git diff --cached --quiet || git commit -m "🛰️ auto: update proxies [ci skip]"
        git push
